### ISSUE TITLE
External issue

### ISSUE THREAD

**Issue by davidlampon** [sergiolucaco/gympad#3]
https://help.github.com/articles/adding-issues-and-pull-requests-to-a-project-board/

**Comment by davidlampon** [comment]
@sergiolucaco check this out for easy managing the project issues on the project page:

<img width="3003" alt="screenshot 2019-01-04 at 16 51 59" src="https://user-images.githubusercontent.com/6107319/50696943-1bfd1400-1041-11e9-96a7-98f0829cb0cb.png">

**Comment by sergiolucaco** [comment]
Yeah ! At first glance I've noticed that all those issues can be drag&dropped in that page but I was wondering if there is like another way more straight forward. Like adding a label to put that specific issue into the proper column of the Kanban. I'm ok doing it like this though.

**Comment by davidlampon** [comment]
You can directly assign it to a project but it makes sense not to have it directly on the todo list as some management has to be in the middle. I think it's still quite ok as long as you have the add card tab opened or just checking for new alerts every time you check the dashboard.

**Comment by sergiolucaco** [comment]
Yeah, totally. It makes sense ! 👯
