### ISSUE TITLE
Set up the boiler plate of the application

### ISSUE THREAD

**Issue by davidlampon** [sergiolucaco/gympad#5]
Use [create-react-app](https://github.com/facebook/create-react-app) package to build the basic structure of the app.

**Comment by sergiolucaco** [comment]
Hello ! I added also commitizen and create the package but I've checked some discrepancies between your PR and mine : 

- ESLINT 
- HUSKY

hmmm.. don't know what to do ! I would like to know more about how to configure those two also !

**Comment by davidlampon** [comment]
Husky let's you add hooks, we need a commit hook for commitlint: https://github.com/marionebl/commitlint

Take a look on this: https://marionebl.github.io/commitlint/#/guides-local-setup

Regarding eslint I didn't add anything special, in fact I think we have the same: https://github.com/sergiolucaco/gympad/pull/13/files#diff-feee3e8dc865fe859f2b31668169945fR17

I think you refer to commitlint, check above 👍

**Comment by sergiolucaco** [comment]
Done ! The PR has been updated accordingly. 

Thanks !

**Comment by davidlampon** [comment]
You can close this one @sergiolucaco
