### ISSUE TITLE
Set up commitizen for coherent commit naming

### ISSUE THREAD

**Issue by davidlampon** [sergiolucaco/gympad#6]
In order to have consistency on the commit messages and keep a healthy git history I encourage you to take a look on this package: https://github.com/commitizen/cz-cli

**Comment by davidlampon** [comment]
Branches doesn't stay long, git history is forever. So I would put the effort on the git commits messaging. I tend to delete branches once they are merged.

For branch naming you can go with the name of the ticket basically (imho) but anyway: https://stackoverflow.com/a/6065944

**Comment by davidlampon** [comment]
Btw: branches can have several commits but once they go to master they have to appear as a . single one.

- https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History
- https://blog.github.com/2016-04-01-squash-your-commits/

In my experience you should go `squash and merge` with a meaningful commit message per branch:

<img width="530" alt="screenshot 2019-01-04 at 17 37 07" src="https://user-images.githubusercontent.com/6107319/50699178-64b7cb80-1047-11e9-912c-55a6c62c590b.png">

**Comment by sergiolucaco** [comment]
Closing this issue since we are not using it for now
