### ISSUE TITLE
Add a rule not to be able to push directly to master

### ISSUE THREAD

**Issue by davidlampon** [sergiolucaco/gympad#8]
Use this as a guide: https://help.github.com/articles/enabling-branch-restrictions/

**Comment by sergiolucaco** [comment]
Hello, 
I checked out the url but I don't find that specific rule. I added a `develop` branch as the default one and apply the same rules to master and develop.

**Comment by sergiolucaco** [comment]
After the setting on github it is no possible to do a direct push to master
